# Generated by Django 5.2.9 on 2026-01-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=255, verbose_name='Mutaxassislik (Daraja)')),
                ('university', models.CharField(max_length=255, verbose_name='Universitet nomi')),
                ('start_date', models.DateField(verbose_name='Boshlangan sana')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugallangan sana')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('end_date'), descending=True, nulls_first=True), '-start_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': [models.OrderBy(models.F('end_date'), descending=True, nulls_first=True), '-start_date']},
        ),
    ]
