# Generated by Django 5.2.9 on 2026-01-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_education_alter_experience_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/clients/')),
                ('body', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('company_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
