# Generated by Django 5.2.9 on 2026-01-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='company',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
