# Generated by Django 5.2.9 on 2026-01-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_clients_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/resume/', verbose_name='Resume oynasi uchun')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
