# Generated by Django 5.2.10 on 2026-01-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contact_read_contact_update_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone', models.TextField(verbose_name='Phone')),
                ('telegram', models.URLField(verbose_name='Telegram')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published?')),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='page_title',
            field=models.CharField(default='Blog', max_length=15),
        ),
        migrations.AddField(
            model_name='home',
            name='two_letter_of_name',
            field=models.CharField(default='AO', max_length=2),
            preserve_default=False,
        ),
    ]
