# Generated by Django 5.2.10 on 2026-01-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_footer_home_page_title_home_two_letter_of_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='telegram',
        ),
        migrations.AddField(
            model_name='footer',
            name='about_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='about_title',
            field=models.CharField(default='About', max_length=80),
        ),
        migrations.AddField(
            model_name='footer',
            name='contact_title',
            field=models.CharField(default='Contact', max_length=80),
        ),
        migrations.AddField(
            model_name='footer',
            name='dribbble',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='phone1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='phone2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='pinterest',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='footer',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
