# Generated by Django 5.2.10 on 2026-01-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_footer_phone_remove_footer_telegram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
