# Generated by Django 5.2.10 on 2026-01-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_home_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='two_letter_of_name',
            field=models.CharField(max_length=2, verbose_name='Two letter of name for logo'),
        ),
    ]
